const express = require('express');
const cors = require('cors');
const health = require('./routes/health');
const registry = require('./routes/registry');
const suites = require('./routes/suites');
const entitlements = require('./routes/entitlements');
const governance = require('./routes/governance');
const app = express();
const port = process.env.PORT || 3000;
app.use(cors());
app.use(express.json());
app.use('/health', health);
app.use('/api', registry);
app.use('/api', suites);
app.use('/api', entitlements);
app.use('/api', governance);
app.get('/', (_req, res) => res.json({ name: 'Enterprise Claude Skills API', status: 'ok' }));
app.listen(port, () => console.log(`Backend running on port ${port}`));
